FROM node:18-alpine as builder

WORKDIR /app
COPY package*.json ./
COPY apps/web/package.json apps/web/

RUN npm ci

COPY . .

RUN npm run build:web

FROM nginx:alpine
COPY --from=builder /app/apps/web/.next/static /usr/share/nginx/html/_next/static
COPY --from=builder /app/apps/web/public /usr/share/nginx/html
COPY apps/web/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80